// <auto-generated />
namespace RestaurantRater.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changed_properties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_properties));
        
        string IMigrationMetadata.Id
        {
            get { return "202002251901251_changed_properties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
